-----------------------------------------------------------------------------------------
| end of epoch   3 | time: 8440.87s | valid loss  3.50 | valid ppl    33.26
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
| test loss  3.51 | test ppl    33.41
-----------------------------------------------------------------------------------------
/opt/conda/conda-bld/pytorch_1518241081361/work/torch/lib/THC/THCTensorIndex.cu:417: long calculateOffset(IndexType, LinearIndexCalcData<IndexType, Dims>) [with IndexType = unsigned int, Dims = 3U]: block: [938,0,0], thread: [40,0,0] Assertion `indexAtDim < data.baseSizes[dim]` failed.
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518241081361/work/torch/lib/THC/generic/THCTensorIndex.cu line=767 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    run(args)
  File "main.py", line 44, in run
    n_layers, hidden_size, print_every)
  File "/home/jianmo/research/expansionNet/final-code/lexicon-title-expansion/train.py", line 256, in trainIters
    loss = train(attr_input, summary_input, summary_input_lengths, title_input, title_input_lengths, target_variable, mask, max_target_len, encoder1, encoder2, encoder3, decoder, embedding, encoder1_optimizer, encoder2_optimizer, encoder3_optimizer, decoder_optimizer, batch_size)
  File "/home/jianmo/research/expansionNet/final-code/lexicon-title-expansion/train.py", line 53, in train
    encoder_out1, encoder_out2, encoder_hidden = encoder3(summary_input, summary_input_lengths, title_input, title_input_lengths, None) # summary encoder
  File "/home/jianmo/anaconda2/envs/venv35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jianmo/research/expansionNet/final-code/lexicon-title-expansion/model.py", line 70, in forward
    out2 = out2[:, x2_unsort_idx, :] # index batch axis
  File "/home/jianmo/anaconda2/envs/venv35/lib/python3.5/site-packages/torch/autograd/variable.py", line 78, in __getitem__
    return Index.apply(self, key)
  File "/home/jianmo/anaconda2/envs/venv35/lib/python3.5/site-packages/torch/autograd/_functions/tensor.py", line 87, in forward
    result = i.index(ctx.index)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1518241081361/work/torch/lib/THC/generic/THCTensorIndex.cu:767
